### ISSUE TITLE
Decouple from that text file?

### ISSUE THREAD

**Issue by kfatehi** [Calit2-UCI/PMUI_Windows_EventListener#3]
check this error. perhaps we can do away with the log file?

this is the first time i have seen this error and i've yet to be able to replicate it... (the c# part of the stack trace). the javascript part ive seen over and over; it's the sneaky one i couldnt get. you are writing the error (stack trace) to STDOUT hence the json parse error!!

the app self-healed by restarting the subprocess after the crash-out; but just FYI in case you want to refactor this out I think the way is to remove that event log file you open a handle to.

```
parser got data 8/4/2016 2:19:00 PM POWER_SETTINGS_CHANGE
{"event": {"timestamp":"8/4/2016 2:19:00 PM","type":"POWER_SETTINGS_CHANGE"}}
parser got data 8/4/2016 2:19:00 PM POWER_SETTINGS_CHANGE
Could not write to file PMUI_EventLog: System.IO.IOException: The process cannot access the file 'C:\cygwin64\home\kfatehi\pm-shell\PMUI_EventLog.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at PMUIWindowsEventListener_Console.CommonUtils.writeToPMUILog(String entry)
JSONStream parse error! Error: Invalid JSON (Unexpected "C" at position 0 in state STOP)
    at Parser.proto.charError (C:\cygwin64\home\kfatehi\pm-shell\node_modules\jsonparse\jsonparse.js:78:16)
    at Parser.proto.write (C:\cygwin64\home\kfatehi\pm-shell\node_modules\jsonparse\jsonparse.js:104:23)
    at Stream.<anonymous> (C:\cygwin64\home\kfatehi\pm-shell\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (C:\cygwin64\home\kfatehi\pm-shell\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)
will reinit
>>> handle power settings change
>>> handle power settings change
{"event": {"timestamp":"8/4/2016 2:19:00 PM","type":"POWER_SETTINGS_CHANGE"}}
syslisten stopped gracefully
{"event": {"timestamp":"8/4/2016 2:19:01 PM","type":"USER_ACTIVE"}}
parser got data 8/4/2016 2:19:01 PM USER_ACTIVE
```

**Comment by kfatehi** [comment]
we finally see the C# stack trace because we got lucky enough to replicate this while also piping your proggie's STDOUT to parent process's STDOUT, not just the JSON parser
